controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
debby_reader:
    path: /debby-reader
    controller: App\Controller\DebbyReaderController::debbyReaderAction